"""Description of the changes

Revision ID: 22056bc6df30
Revises: 8a65b2c0dc8a
Create Date: 2025-02-21 19:43:55.302880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22056bc6df30'
down_revision = '8a65b2c0dc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('attendance_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_status', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
