"""Description of the changes

Revision ID: 2ff58f051330
Revises: accd44652be0
Create Date: 2025-02-21 19:13:30.318179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff58f051330'
down_revision = 'accd44652be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('Paid', 'Unpaid', name='payment_status'), nullable=True))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=6), nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
