"""Description of the changes

Revision ID: 3c0a8876ff27
Revises: 96cf799278e4
Create Date: 2025-02-26 18:54:50.187294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0a8876ff27'
down_revision = '96cf799278e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=False))
        batch_op.alter_column('transaction_code',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('transaction_code',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
