"""Description of the changes

Revision ID: 4b1f393559cd
Revises: 22056bc6df30
Create Date: 2025-02-25 17:57:39.598621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1f393559cd'
down_revision = '22056bc6df30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('currend_balance', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('changes_amount', sa.Float(), nullable=False),
    sa.Column('transaction_code', sa.String(length=500), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('date_paid')
        batch_op.drop_column('transaction_code')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('transaction_code', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('date_paid', sa.DATETIME(), nullable=True))

    op.drop_table('transaction')
    # ### end Alembic commands ###
