"""Description of the changes

Revision ID: 4f95af13a194
Revises: cd0e0a9b3d74
Create Date: 2025-02-26 10:07:02.511229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f95af13a194'
down_revision = 'cd0e0a9b3d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('transaction_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_code', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
