"""Description of the changes

Revision ID: 62cab0bc00e3
Revises: 4b1f393559cd
Create Date: 2025-02-25 18:26:01.640067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cab0bc00e3'
down_revision = '4b1f393559cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('amount_pay', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('selected_fines_total_amount', sa.Float(), nullable=False))
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('currend_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currend_balance', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.FLOAT(), nullable=False))
        batch_op.drop_column('selected_fines_total_amount')
        batch_op.drop_column('amount_pay')
        batch_op.drop_column('current_balance')

    # ### end Alembic commands ###
