"""Description of the changes

Revision ID: 697f068db25a
Revises: e1ec3e1312c9
Create Date: 2025-02-19 20:27:43.293709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697f068db25a'
down_revision = 'e1ec3e1312c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'schedule', ['event_id'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sched_activities', ['activity_id'], ['id'])
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
