"""Description of the changes

Revision ID: 8a65b2c0dc8a
Revises: 2ff58f051330
Create Date: 2025-02-21 19:32:56.448215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a65b2c0dc8a'
down_revision = '2ff58f051330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=6), nullable=True))

    # ### end Alembic commands ###
