"""Description of the changes

Revision ID: 96cf799278e4
Revises: 70ce8afece92
Create Date: 2025-02-26 18:15:44.416941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cf799278e4'
down_revision = '70ce8afece92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('transaction_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_code', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['transaction_code'], ['transaction_code'], ondelete='CASCADE')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
