"""Description of the changes

Revision ID: cd0e0a9b3d74
Revises: 51a1d22f17d2
Create Date: 2025-02-26 10:01:55.544742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0e0a9b3d74'
down_revision = '51a1d22f17d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_payment')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_code', sa.String(length=100), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['transaction_code'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transaction_code',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['transaction_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('transaction_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('transaction_code')

    op.create_table('_alembic_tmp_payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('date_paid', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
