"""Description of the changes

Revision ID: dfaba7713945
Revises: 62cab0bc00e3
Create Date: 2025-02-25 20:44:00.126634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfaba7713945'
down_revision = '62cab0bc00e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_paid', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_paid', sa.DATETIME(), nullable=True))
        batch_op.drop_column('transaction_date')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('date_paid')

    # ### end Alembic commands ###
