"""Description of the changes

Revision ID: e6b05e72f77a
Revises: 4f95af13a194
Create Date: 2025-02-26 11:00:21.003439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b05e72f77a'
down_revision = '4f95af13a194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_code', sa.String(length=500), nullable=False))
        batch_op.create_unique_constraint(None, ['transaction_code'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_code',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'payment', ['transaction_code'], ['transaction_code'], ondelete='CASCADE')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])
        batch_op.alter_column('transaction_code',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transaction_code')

    # ### end Alembic commands ###
